name: Розгортання на Netlify

on:
  push:
    branches:
      - main # Пайплайн запускається, коли код пушиться в гілку 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 1. Вивантажити код з репозиторію
      


      - name: Розгортання на Netlify
        uses: netlify/actions/cli@master # 2. Використання офіційної дії для Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          publish-dir: './'
